---
- hosts: all
  vars:
    # basic vars
    user_name: user
    # Fail2ban config vars
    fail2ban_mail_dest: "root@localhost"
    # iptables variables
    ssh_port: 22
    # Git variables
    git_runner_dir: "/opt/projects/actions-runner/"
    project_dir: "/opt/projects/"
    git_repo: "Some HTTP Repo"
    git_branch: "main"
    git_repo_url: "https://github.com/psejerman/node-cicd-docker"
    project_name: "node-cicd-docker"
    project_folder_root: "/some/path/"
    git_user_name: "Peter Sejerman"
    git_user_id: "psejerman"
    git_user_email: "p.sejerman@gmail.com"
    git_runner_service_name: "actions.runner.{{ git_user_id }}-{{ project_name }}.{{ ansible_hostname }}"

  tasks:
  - name: Import tasks from other files
    block:
      - include_tasks: install_prequisites.yml
      - include_tasks: install_docker.yml
      - include_tasks: configure_iptables.yml
      - include_tasks: configure_fail2ban.yml
      - include_tasks: install_github_runner.yml
      #- include_tasks: test.yml ## Playground for module tests
      ## Setup repo for commits and pushes from target host (not needed for production)
      #- include_tasks: setup_git.yml